{
  consumer_key: "WrFiASTYdEk5Y0VSFQZ211MdR",
  consumer_secret: "9U3ZhwflnRCEmgmIs5GU3nCXtJ9czK9RsgaGAxv45qZcAV1JoO",
  access_token: "3429855759-cEUza6Zagn5PMsL1YxH3bMmnziupVq9i2XEk15w",
  access_token_secret: "BJHoQUEj9LGMIlK28Q5Bt8p7k1M9ltU7WkB1C8KM5DALY"
}